### ISSUE TITLE
tests: red

### ISSUE THREAD

**Issue by adams-sarah** [GoogleCloudPlatform/google-cloud-go#633] opened 2017-05-18 18:57 UTC
We need to disable integration tests for the time being. I don't think any of us have the cycles to fix ATM.
They are not helpful ATM. It is not helpful to have an always-red build.
It also looks awful for users coming to this package, that our badge is always red.

Further, once someone does have cycles to do some work, we need to remove the tests which are flaky. Better to remove and write anew another time than to disable, as the test itself is likely not great. 
We also need to remove any timeout or retry logic higher than the clients (is any of this left in our tests)? If the client is failing so badly that we need to retry at the level of the test, we need to fix the client not the test.
There should be no timeout logic in our tests themselves, unless absolutely unavoidable.
Finally, for tests which are flaky b/c the server is flaky, we need to mock them out with some kind of rpc-replay or something. It is better to know that our code is 100% good with a green build, than for 100% red build whose failing cause is not obvious (server or client). If the server changes, we can catch with local builds or periodic builds which actually hit the server.

Moral of the story: our builds are red every time. we need to fix.
short term solution == turn off integration tests for all pkgs which have 1 flaky test.

@pongad @jba

**Comment by rakyll** [comment] 2017-05-18 19:27
FYI, I removed the badge via https://github.com/GoogleCloudPlatform/google-cloud-go/commit/954cc483cacf7e37587fc7a76996571a40c7356c, so no one else sees that integration tests are failing.

**Comment by adams-sarah** [comment] 2017-05-18 20:08
oh nice. thx jbd.
I still think that it is better to have no integration tests for some pkgs temporarily than all integration tests and builds are always red. there's no point in even running the tests at all in travis as it stands today.

**Comment by jba** [comment] 2017-05-18 20:14
I disagree. I am now checking out every failed run, and attempting to correct it. Having that ongoing testing is valuable to me.

The most important thing is not having the badge. 

Maybe you can remove yourself from just the Travis emails?

**Comment by adams-sarah** [comment] 2017-05-18 20:19
I agree about ongoing testing being valuable. But when I merge code and the build is always red, there's not a clear signal as to whether my code broke things or not.

I'm not receiving emails. And the badge is an afterthought-concern. I'm worried about merging broken code.

we've been trying to fix the build for months now, and it's still red. I'd like to see flaky tests removed with a todo to write a new one, and one-by-one go through and write these new tests, perhaps with a mock or a new strategy. I'd rather see this than one-by-one going through and fixing, b/c in the meantime, the build is still red.

**Comment by jba** [comment] 2017-05-18 20:24
> If the client is failing so badly that we need to retry at the level of the test, we need to fix the client not the test.

I strongly disagree. Take https://code-review.googlesource.com/c/13111/ as an example. It waits for an eventually consistent system to settle. (That waiting looks like a retry because the only way to wait is to poll.) It's not our clients' job to paper over eventual consistency. Doing so would defeat the design choice made by the service: to prefer fast response over consistency.

Maybe we shouldn't be testing an eventually consistent system in this way at all. We can discuss that separately. Here I'm just addressing the quoted point.

**Comment by adams-sarah** [comment] 2017-05-18 20:30
Ah duh, ^ you are totally right. I misspoke completely.
+1 to thinking about writing the tests a different way. I think we should talk about this. 

I still would rather have a green build now as opposed to later. So (as someone who does not frequently contribute to this codebase anymore, I realize) I would prefer to remove these tests now with a todo and write new ones one-by-one, giving us an immediately green build to work with, instead of fixing tests one-by-one until build is green again. especially considering this is what we've been doing almost since I joined, and the build is still red :(.

**Comment by jba** [comment] 2017-05-18 20:44
> But when I merge code and the build is always red, there's not a clear signal as to whether my code broke things or not.

Agreed, this is bad. Hopefully, we all run `go test` locally before submitting. And as long as someone is grepping the Travis build log on each failure, there is still a signal about the breakage, it's just harder to find.

As an example of the value of Travis, recently I submitted 2 (!) CLs that used "context" instead of "golang.x/net/context". Those only broke the 1.6 build. Although I do run `go test` religiously, I do not run it on all 3 supported Go versions. Travis does that for me.

For me, the red build is a signal that I need to fix something, maybe not my latest CL. I worry that removing tests will remove _that_ signal.

> we've been trying to fix the build for months now

I finally have bandwidth for this, so I think things will change quickly. I feel like this is bad timing. Give me some time! 

> I'd like to see flaky tests removed with a todo to write a new one, and one-by-one go through and write these new tests

I'm nervous about removing tests. TODOs are notorious for never getting done.

How about: if I don't have time, remove the test, but if I can fix within a couple of hours, do so? (Speaking of which, will you reconsider https://code-review.googlesource.com/c/13111 in light of our discussion in previous comments?)

**Comment by adams-sarah** [comment] 2017-05-18 20:47
OK! I understand.
Can we put a time bound on the red builds maybe? Like a month?
And after that we come up with a new strategy?

**Comment by adams-sarah** [comment] 2017-05-18 20:49
Are there still tests which are flaky b/c server sometimes gives a 500?

**Comment by jba** [comment] 2017-05-18 22:02
Sure, a month is good.

Meanwhile, I'd like to keep talking about this, if only to record my thoughts. Let's talk about three possible CI test strategies: true integration tests, fakes and RPC replay.

Integration tests subject you to all the vagaries of the service. If the service is flaky, your tests are flaky. That is not great. On the other hand, you get continuous feedback on the actual state of the world. You learn whether some part of a system is eventually consistent (the docs rarely say so) or whether your client should be retrying somewhere it's not. For that reason, I consider integration tests the gold standard.

A good fake maintained by the service team is the next best thing. There is a decent chance that the fake's behavior matches the actual behavior. I would consider replacing integration tests with emulators in our CI, where available. However, these still don't replace true integration tests because the fake's failure modes are unlikely to be anything like the actual service's. In fact, the fake is unlikely to ever fail, while the service is unlikely to always succeed.

Writing and maintaining our own fake is fine as a unit test (logging has that), but is inadequate as a replacement for an integration test. We're unlikely to do a thorough job of matching behavior, and we can't keep up with changes to the actual service.

Originally I liked the idea of RPC replay. But when I realized it is just an automated mock, I got less excited. True, you are testing against what the service actually did at one point and not what you think it does, but in both cases you can be out of date. There's a further technical problem that I'm not sure is soluble: how to handle concurrency and nondeterminism. Say you record two calls with identical requests concurrently, but the server is stateful so they give back different answers. How do you match requests with responses on replay? I think the problem is worse for Go because there are no goroutine identifiers. If this means that we can't write concurrent RPCs in our tests, that would be bad.

I guess I'd be fine with either emulators or RPC replay as long as we had a second CI config, run less frequently perhaps (weekly instead of daily?), that ran the integration tests.

**Comment by jba** [comment] 2017-05-18 22:03
> Are there still tests which are flaky b/c server sometimes gives a 500?

The vision tests come to mind. Since we're decommissioning the handwritten client, I'd be OK removing them. There is a limited smoke test in the generated client which is adequate.

I can't recall any other 500s.

**Comment by jba** [comment] 2017-08-08 16:35
Travis has been looking pretty good. Closing this.

**Closed by jba** 2017-08-08 16:35 UTC
