### ISSUE TITLE
storage: segmentation violation

### ISSUE THREAD

**Issue by iamacarpet** [GoogleCloudPlatform/google-cloud-go#1015] opened 2018-05-31 15:01 UTC
## Client

Storage (GCS)

## Describe Your Environment

App Engine SDK, tried api_version: go1 (Go 1.8) and api_version: go1.9 (Go 1.9)

## Expected Behavior

Trying to create and write to a zip file, by reading other files from GCS and writing them to the zip stream.

Excerpt of code here: https://gist.github.com/iamacarpet/bb510932835d942fa7158b6b8d51f864

## Actual Behavior

2018/05/31 14:52:08 INFO: Opening GCS writer...
2018/05/31 14:52:08 INFO: Opening ZIP writer...
2018/05/31 14:52:08 INFO: Listing snapshot directory...
2018/05/31 14:52:08 INFO: opening file reader...
2018/05/31 14:52:08 INFO: opening file writer inside zip...
2018/05/31 14:52:08 INFO: copying data into zip...
2018/05/31 14:52:08 INFO: closing reader...
2018/05/31 14:52:08 INFO: add file done...
2018/05/31 14:52:08 INFO: opening file reader...
2018/05/31 14:52:08 INFO: opening file writer inside zip...
2018/05/31 14:52:08 INFO: copying data into zip...
2018/05/31 14:52:08 INFO: closing reader...
2018/05/31 14:52:08 INFO: add file done...
2018/05/31 14:52:08 INFO: opening file reader...
2018/05/31 14:52:08 INFO: opening file writer inside zip...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x9527dd]

goroutine 324 [running]:
google.golang.org/api/storage/v1.(*ObjectsInsertCall).Context(...)
        $GOPATH/src/cloud.google.com/go/storage/writer.go:118
cloud.google.com/go/storage.(*Writer).open.func1(0xc4201fc5a0, 0xc4204c3c80, 0xc42000c208, 0xc420084bd0, 0x1, 0x1)
       $GOPATH/src/cloud.google.com/go/storage/writer.go:121 +0x10d
created by cloud.google.com/go/storage.(*Writer).open
        $GOPATH/src/cloud.google.com/go/storage/writer.go:108 +0x47d

Any idea what is going wrong?

I've updated the libraries to make sure I'm on the latest and still the same issue.

Regards,
iamacarpet

**Comment by jadekler** [comment] 2018-05-31 15:08
It seems to be failing on [`zWriter, err := zipWriter.Create(shortname)`](https://gist.github.com/iamacarpet/bb510932835d942fa7158b6b8d51f864#file-zip_generate_excerpt-go-L92) - is that correct? What is `zip.NewWriter`?

**Comment by iamacarpet** [comment] 2018-05-31 15:12
Nevermind, it was because I was closing the storage client in openFileWriter:

```go
        client, err := storage.NewClient(ctx)
	if err != nil {
		log.Errorf(ctx, "Error getting GCS Client: %s", err)
		return nil, err
	}
	defer client.Close()
```

Fixed that and it now works as expected.

`zip.NewWriter` is part of the "archive/zip" package.

Would you like me to close, or would you like to investigate why it gave such a weird segmentation error?

**Comment by jadekler** [comment] 2018-05-31 15:19
Ahh! That make sense. I think we can close this; using a client that has been previously closed is non-intended behavior.

**Closed** 2018-05-31 15:19 UTC
Labels: api: storage
