### ISSUE TITLE
Storage: Add generation # for reader

### ISSUE THREAD

**Issue by nomis52** [GoogleCloudPlatform/google-cloud-go#1105] opened 2018-08-17 16:11 UTC
Please expose the generation number in the [Reader. ](https://godoc.org/cloud.google.com/go/storage#Reader)

Without this clients need to make two API calls:

```
  attrs, err := obj.Attrs(ctx)
  if err != nil {
    return err
  }

  // lock the read to the generation.
  readObj := h.obj.Generation(attrs.Generation)
  r, err := readObj.NewReader(ctx)
```

**Comment by jba** [comment] 2018-08-17 17:31
I'm not sure what you're asking for. From your code, it looks like you want to fix the generation that you're reading, and your code does that (modulo #1106). I don't see a way around the `Attrs` call to get the generation.

**Comment by nomis52** [comment] 2018-08-18 16:43
Sorry I wasn't specific enough. We need to know the generation of the object that was read. The only way I can find to do this right now is to call Attrs() to get the current generation and then lock the read to that generation.

If we expose the X-Goog-Generation header via the Reader it will save a network round trip.

**Comment by jadekler** [comment] 2018-08-31 17:47
I'm a bit hesitant to do this. I _think_ the bigger picture is every call-related data structure (e.g. reader, writer, objectHandle, etc) should then record the generation number. @frankyn what do you think?

**Comment by frankyn** [comment] 2018-08-31 20:54
@nomis52, If I understand carefully, you want to read an object and get the response header `X-Goog-Generation`, then use that generation value for follow-up reads/writes. Is this accurate?

**Comment by nomis52** [comment] 2018-08-31 20:55
@frankyn: correct, we need this to implement optimistic concurrency control.

**Comment by jadekler** [comment] 2018-09-04 21:12
Related: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1132

**Comment by frankyn** [comment] 2018-09-06 04:15
At the moment the design is succinct, you make a request for object metadata and get the generation, then use the generation for follow-up optimistic concurrent operations with reads/writes/updates.

The concern I have is now there will be multiple ways of requesting a subset of information not all metadata in a call response. I understand the reduction of requests from two to one for generation in this case, but I'm not convinced. I think it confuses the lifecycle of the client. 

@nomis52 could you provide use cases of how you're using optimistic concurrency? _I'm assuming at the moment that you're speaking with regards to [Concurrency Control with GCS](https://cloud.google.com/storage/docs/gsutil/addlhelp/ObjectVersioningandConcurrencyControl)_

**Comment by jadekler** [comment] 2018-09-06 16:56
My concern is similar - I'm not sure that we get all the headers that would make up an ObjectAttr, which means we need something else - ObjectAttrLite or something heh. On top of this messiness, there may also be a number of similar places that would be justified in getting this object once we go down this road, which could mean muddying the waters beyond reader.

**Comment by frankyn** [comment] 2018-09-06 17:36
cc: @coryan
@jadekler from running a Get request:
```
X-goog-metageneration: 1
Content-location: https://www.googleapis.com/storage/v1/b/coderfrank/o/new-object?alt=media
Content-disposition: attachment
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Vary: Origin,X-Origin
Content-length: 3324
Cache-control: no-cache, no-store, max-age=0, must-revalidate
Etag: CNbnu6HMot0CEAE=
X-goog-generation: 1536106934760406
Pragma: no-cache
X-guploader-uploadid: AEnB2UoIpSh9dmauihFSzlk-RnPXdVOVw_ZOZpNbAFRQbYq6Hs7-i0NsDUmuv6RlPPe0wcKZB2S7SCCJlBRfCLAkvxMf7r5cvw
Date: Thu, 06 Sep 2018 17:23:02 GMT
X-goog-hash: crc32c=EhUJRQ==
Content-type: plain/text
X-goog-storage-class: STANDARD
```

At a brief look `md5` and `custom metadata` metadata is missing so `ObjectAttrLite` would make sense as a full ObjectAttr isn't returned. 

I'm curious how this would look if implemented as a surface example.

**Comment by vangent** [comment] 2018-09-06 17:54
If by "custom metadata" you mean the `Metadata map[string]string`, I'm pretty sure that it is in fact returned; see #1132 where I requested it be exposed by Reader (marked as a dupe of this one). I see headers like  `X-Goog-Meta-` being returned in the HTTP response to the request that `Object.NewRangeReader` makes.

**Comment by nomis52** [comment] 2018-09-08 01:49
@frankyn 

Here is the code:

`
func (h *handle) Update(ctx context.Context, f UpdateFn) error {                                                                                                                     
  for i := 0; i < _retries; i++ {
    obj, generation, err := h.readWithGeneration(ctx)
    if err != nil {
      return err
    }

    if err := f(obj); err != nil {
      return err
    }

    if err = h.write(ctx, obj, storage.Conditions{GenerationMatch: generation}); err == nil {
      return nil
    }

    if e, ok := err.(*googleapi.Error); ok && e.Code == http.StatusPreconditionFailed {
      // Write collision, retry.
      continue
    }
    return err
  }
  return errUpdateFailed
}`

The readWithGeneration() function is the code at the top of this issue.

**Comment by jadekler** [comment] 2018-09-09 05:00
re https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1132#issuecomment-419690953, I'm not sure we can do the metadata. Generation seems very doable rthough.

**Comment by frankyn** [comment] 2018-09-11 23:00
@jadekler is addressing this issue to expose the generation among other attributes. Will follow-up on #1132 for metadata. Take one issue out at a time.

**Closed** 2018-09-14 15:38 UTC
Labels: api: storage, type: feature request

**Comment by jadekler** [comment] 2018-09-14 15:46
You should now be able to use `Reader.Attrs.Generation`. 👍

**Comment by jadekler** [comment] 2018-09-14 23:36
This coming Monday.

**Comment by nomis52** [comment] 2018-09-14 23:38
Awesome. Thanks.
