### ISSUE TITLE
Getting "Mutation is missing operation" error when trying to do datastore.Client.Put

### ISSUE THREAD

**Issue by anasanzari** [GoogleCloudPlatform/google-cloud-go#879] opened 2018-02-01 15:53 UTC
rpc error: code = 3 desc = Mutation is missing operation.
```
key, err := client.Put(ctx, taskKey, in)
	if err != nil {
		log.Error(err)
		return nil, err
	}
}
```

**Comment by jadekler** [comment] 2018-02-01 16:26
Hi @anasanzari, thanks for reaching out. Could you describe the datatype of `in`? I'm unable to repro the problem using the example code provided at https://godoc.org/cloud.google.com/go/datastore (which has a similar `client.Put` call as yours), but because of [this issue](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3361) I wonder whether you're passing an unsupported type? Either way I'd like to debug this further if you could provide additional details.

**Comment by anasanzari** [comment] 2018-02-02 11:37
Type of `in` is `interface{}`. It's actually a pointer to some user defined `struct`.
This is the govendor configuration i'm using:
```
{
   "checksumSHA1": "0axPMz2dNK+QK/2wFBj/o1ulHjY=",
   "path": "cloud.google.com/go/datastore",
   "revision": "0e0ec87d77f27fbf630f4599b7134faba020634f",
   "revisionTime": "2016-12-13T00:09:24Z"
}
```

go version go1.7.6 linux/amd64

**Comment by jadekler** [comment] 2018-02-02 17:15
@anasanzari Thanks for the info. Could you describe the struct, please? Or even better, could you show me the code for the struct? I'd like to try sending the same type of data you are to see if I can reproduce the issue.

**Comment by jadekler** [comment] 2018-02-12 20:29
ping @anasanzari

**Comment by jadekler** [comment] 2018-02-14 23:27
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Closed by jadekler** 2018-02-14 23:27 UTC
Labels: api: datastore, priority: p1
