### ISSUE TITLE
Bigtable Emulator: issue when put + get with multiple columns

### ISSUE THREAD

**Issue by zzorba** [GoogleCloudPlatform/google-cloud-go#623] opened 2017-05-10 18:52 UTC
I'm seeing issues when running against the bigtable emulator.  

If a Put operation is executed setting multiple keys, followed some time later by a Get operation of the same values, not all data is returned.  Some of the columns will be returned, others will not.

The following test seems to fail > 50% of the time when run against the emulator, yet succeeds 100% of the time when run against a developer cloud bigtable cluster.  I haven't seen this happen when a single put is executed, but serializing the same put requests over multiple put commands 
 seems to exhibit the same behavior.

```
try (Table table = connection.getTable(tableName)) {
      Put put = new Put("multiPutKey".getBytes())
          .addColumn("cf1".getBytes(), "column1".getBytes(), "hi".getBytes())
          .addColumn("cf1".getBytes(), "column2".getBytes(), "there".getBytes())
          .addColumn("cf1".getBytes(), "column3".getBytes(), "mr".getBytes())
          .addColumn("cf2".getBytes(), "column4".getBytes(), "grinch".getBytes());
      table.put(put);

      Get get = new Get("multiPutKey".getBytes())
          .addFamily("cf1".getBytes())
          .addFamily("cf2".getBytes());
      Result result = table.get(get);

      // At least 50% of the time, one of these asserts will fail when running with emulator
      assertNotNull(result.getColumnLatestCell("cf1".getBytes(), "column1".getBytes()));
      assertTrue(Arrays.equals(
          "hi".getBytes(),
          result.getColumnLatestCell("cf1".getBytes(), "column1".getBytes()).getValueArray()));

      assertNotNull(result.getColumnLatestCell("cf1".getBytes(), "column2".getBytes()));
      assertTrue(Arrays.equals(
          "there".getBytes(),
          result.getColumnLatestCell("cf1".getBytes(), "column2".getBytes()).getValueArray()));

      assertNotNull(result.getColumnLatestCell("cf1".getBytes(), "column3".getBytes()));
      assertTrue(Arrays.equals(
          "mr".getBytes(),
          result.getColumnLatestCell("cf1".getBytes(), "column3".getBytes()).getValueArray()));

      assertNotNull(result.getColumnLatestCell("cf2".getBytes(), "column4".getBytes()));
      assertTrue(Arrays.equals(
          "grinch".getBytes(),
          result.getColumnLatestCell("cf2".getBytes(), "column4".getBytes()).getValueArray()));
    } catch (IOException e) {
      e.printStackTrace();
    }
```

**Comment by garye** [comment] 2017-05-23 20:23
Sorry for the delay here. I can't reproduce this with the version that's in development now. If you don't mind trying it out I can put it up on GCS so you can use it until the gcloud version is released. Are you running on linux or a mac?

**Comment by zzorba** [comment] 2017-05-23 21:13
I'm running locally on mac OSX, though I could test out the linux version as well on our CircleCI build.

**Comment by garye** [comment] 2017-05-23 21:28
Great! I have a linux build ready to go, let me know if you want an OSX one later:

```
$ wget https://storage.googleapis.com/cloud-bigtable-test/cbt-emulator-test.tar.gz
2017-05-01 14:14:00 (57.2 MB/s) - ‘cbt-emulator-test.tar.gz’ saved [3659284/3659284]

$ tar zxvf cbt-emulator-test.tar.gz 
cbtemulator

$ ./cbtemulator -port=8081
Cloud Bigtable emulator running on 127.0.0.1:8081
```

**Comment by garye** [comment] 2017-05-23 21:33
Actually, here's a mac version, too: https://storage.googleapis.com/cloud-bigtable-test/cbt-emulator-test-osx.tar.gz

**Comment by zzorba** [comment] 2017-05-23 22:09
Thanks @garye, the issues I was seeing appear to be completely fixed on the mac binary.  I'll test out the linux version first thing tomorrow morning to confirm, but things are looking good so far.

Thanks for your help.

**Comment by garye** [comment] 2017-05-23 22:11
Ok glad to hear that. Let's keep this open until the new release makes it way to gcloud.

**Comment by zzorba** [comment] 2017-05-24 15:11
I can confirm the linux build works as well.

**Comment by garye** [comment] 2017-05-24 15:36
Thanks for checking!

**Comment by garye** [comment] 2017-06-07 15:44
Fixed in gcloud 158:
https://cloud.google.com/sdk/docs/release-notes

**Closed by garye** 2017-06-07 15:44 UTC
Labels: bigtable, bug, P2+
