### ISSUE TITLE
bigquery add use standard sql

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/google-cloud-go#281] opened 2016-06-29 15:26 UTC
I have try to use standard sql and I do not find please can you add this awesome feature.

**Comment by jba** [comment] 2016-06-29 17:22
We'll look into it.

**Comment by okdave** [comment] 2016-07-06 13:50
@albertog can you give more details about exactly what you're trying to achieve? Are you saying you'd like the package to be compatible with [`datastore/sql`](https://golang.org/pkg/database/sql/), or that you'd like the query syntax to change?

**Comment by albertog** [comment] 2016-07-06 13:53
My request is to allow use new syntax sql

https://cloud.google.com/bigquery/sql-reference/enabling-standard-sql

thanks

**Comment by calumjones** [comment] 2016-07-06 14:38
I believe this is the same issue that i came across, and the issue is down to the UseLegacySql value being a bool rather than a pointer to a bool.
It can never be set to false because of the 'omitempty' flag on the value, when it is converted to JSON, if the UseLegacySql value is set to false, it will be removed as Go classes false as the "empty" value for a bool

**Comment by chrisprobst** [comment] 2016-09-08 13:08
What's the status of this issue? I need this option. Any workarounds?

**Comment by jba** [comment] 2016-09-08 15:09
It's going to happen by September 30.

**Comment by chrisprobst** [comment] 2016-09-30 09:26
@jba Is this still true? :-)

**Comment by jba** [comment] 2016-09-30 11:25
It's there: https://godoc.org/cloud.google.com/go/bigquery#QueryUseStandardSQL. We forgot to mark the bug fixed. (It's a duplicate of #326.)

Fixed by 9c1098a4debc9bf1073ed0e4872b12bd916243d8.

**Closed by jba** 2016-09-30 11:25 UTC
Labels: bigquery, enhancement

**Comment by chrisprobst** [comment] 2016-09-30 11:28
Sweet, thanks.

**Comment by chrisprobst** [comment] 2016-10-04 09:00
@jba I'm not sure, if this is fixed.

I'm not sure how QueryUseStandardSQL() can be used for querying, client.Query().Read(, ..) only accepts ReadOptions. 

I'm probably doing something wrong, any ideas ? 

Thanks!

**Comment by adams-sarah** [comment] 2016-10-04 18:54
@shantuo might be able to help.

**Comment by shantuo** [comment] 2016-10-04 21:36
Yes, Copy() should work. But it may change before BigQuery going to Beta.
