### ISSUE TITLE
cloudspanner: Inconsistent behavior when using gcloud Application Default Credentials vs GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by hostirosti** [GoogleCloudPlatform/google-cloud-go#1049] opened 2018-06-28 21:59 UTC
## Client

tested with Cloud Spanner and Cloud Pub/Sub
--> issue only shows for Cloud Spanner of the 2 tested ones

## Describe Your Environment

zsh on Mac

## Expected Behavior

Same auth behavior between all used authentication methods 
(1) gcloud application default creds
(2) ENV GOOGLE_APPLICATION_CREDENTIALS
(3) explicit service-account.json key file

When setting up a new Cloud Spanner client with a context that is canceled after obtaining an instance of the client I see the following behavior for all subsequent calls:
```
ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
c, err := instance.NewInstanceAdminClient(ctx)
if err != nil {
	return nil, err
}
cancel()

req := &instancepb.ListInstancesRequest{
	Parent: "projects/<YOUR_PROJECT>",
}

ctx,_ = context.WithTimeout(context.Background(), 30*time.Second)
c.ListInstances(ctx, req)
```
Expected behavior for all 3 auth methods should be either succeed or fail. 
To be considered, for Cloud PubSub the current behavior is that for all 3 auth methods all subsequent calls using the client (obtained with an after instantiation canceled context) succeed.

## Actual Behavior

(1) rpc error: code = Unauthenticated desc = transport: context canceled
(2) succeeds
(3) succeeds

## Related issues
#1045 - spanner: Application Default Credentials fail to work after a timeout

**Comment by broady** [comment] 2018-06-28 22:01
to clarify, (2) succeeds only because the environment variable points to service account creds.

I think this is a dupe of #1045.

**Comment by broady** [comment] 2018-06-28 22:02
Follow-up from @hostirosti on chat:

package `pubsub` doesn't exhibit this behavior, so it's probably limited to `spanner`?.

**Comment by jba** [comment] 2018-07-03 13:43
Cannot reproduce successful pubsub behavior. My program
```
    ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
    c, err := pubsub.NewClient(ctx, "<PROJECT>")
    if err != nil {
        log.Fatal(err)
    }
    cancel()

    ctx, _ = context.WithTimeout(context.Background(), 30*time.Second)
    fmt.Println(c.Topic("foo").Exists(ctx))
```
prints
```
false rpc error: code = Unauthenticated desc = transport: context canceled
```

**Comment by hostirosti** [comment] 2018-07-03 18:19
Indeed, I do that with the same context but setup a pull subscription with a new (different) context and that still works even though the ctx from creating the client is canceled. 

```
type PubSubClient struct {
	*pubsub.Client
	subscription *pubsub.Subscription
	cancelPull   context.CancelFunc
}

func (svc *PubSubClient) setupPull(f func(ctx context.Context, msg *pubsub.Message)) error {
	ctx, cancel := context.WithCancel(context.Background())
	svc.subscription.ReceiveSettings.MaxOutstandingMessages = 10
	svc.cancelPull = cancel
	err := svc.subscription.Receive(ctx, f)
	if err != nil {
		cancel()
		return err
	}
	return nil
}

```

**Comment by jba** [comment] 2018-07-06 10:30
`Subscription.Receive` is a special case. It has a complicated relationship with cancellation. See [the code](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/subscription.go#L462). Because the actual RPCs use `context.Background()`, it isn't possible to cancel them directly. That is necessary to preserve the semantics of `Receive` (particularly that all acks are transmitted). 

Is there a reason you need to do this, or are you just pointing out the inconsistency? If there's something you're trying to accomplish, let's try to find a different way.

**Comment by jba** [comment] 2018-08-13 18:31
Closing this due to lack of response. If there's still an issue, feel free to reopen.

**Closed by jba** 2018-08-13 18:31 UTC
Labels: :rotating_light:, api: spanner, priority: p1, type: question
