### ISSUE TITLE
storage: tests fail when using modules

### ISSUE THREAD

**Issue by hdonnay** [GoogleCloudPlatform/google-cloud-go#1138] opened 2018-09-06 18:01 UTC
## Client

storage

## Describe Your Environment

A program using modules:

```sh
#!/bin/sh
set -ex
t=$(mktemp -d)
trap 'rm -r $t' EXIT
cd $t
cat >ex.go <<.
package main

import (
	_ "cloud.google.com/go/storage"
)

func main() {
	println("example")
}
.
go mod init example
go get github.com/google/martian@master # broken
go test all
```

## Expected Behavior

tests pass

## Actual Behavior

```
2018/09/06 13:57:37 creating bucket "go-integration-test-20180906-64657522195962-0001": googleapi: Error 400: Unknown project id: , invalid
FAIL	cloud.google.com/go/storage	0.481s
```

(`golang.org/x/sys/unix` also fails, but that's out-of-scope)

**Comment by hdonnay** [comment] 2018-09-06 20:57
No, I'm attempting to follow the steps outlined [here](https://github.com/golang/go/wiki/Modules#how-to-prepare-for-a-release).

It seems like integration tests should be skipped in this case.

**Comment by jadekler** [comment] 2018-09-06 23:01
`go test all` seems to run integration tests AFAICT. Have you tried `go test all -short`?

Also, `go test all` on my machine succeeded - likely because environment variables are set as described in the CONTRIBUTING.md that @jba linked. I'll close this issue for now since it seems like things are working as intended.

**Closed by jadekler** 2018-09-06 23:01 UTC
Labels: api: storage
