### ISSUE TITLE
Pubsub modify ack deadline trigger

### ISSUE THREAD

**Issue by Tang8330** [GoogleCloudPlatform/google-cloud-go#629] opened 2017-05-16 19:03 UTC
I was debugging this morning with Kir

We had an incident where majority of our ack operations ended up being modify ack deadline. 
My immediate questions are:
1) What is modify acknowledgement deadline?
2) What could have caused this? What triggers the modify ack deadline to be called?

Thank you!

The SHA we are currently on is -- `df9740f981cff9eb64dd60b92d8b9f38609f5ebd`

**Comment by jba** [comment] 2017-05-16 21:33
The ack deadline is how long the server waits for your client to ack the message before sending it out again. A client can modify the ack deadline of a message it has received if it needs more time than expected to work on it. For instance, if the ack deadline is 10 seconds and you notice that you're still processing the message after 8 seconds and need more time, you could modify the ack deadline by extending it.

Another reason to modify the ack deadline is if you know you can't handle the message. Then you'd modify it to zero, so it is immediately re-sent to another client. We call this "nacking" the message.

The Go client calls `ModifyAckDeadline` for both reasons. We call it automatically on each message that you haven't yet called `Message.Ack` on, to extend the ack deadline up to `ReceiveSettings.MaxExtension`. That is for your convenience, so you don't have to keep track of the time yourself. We also call `ModifyAckDeadline` with zero if you call `Message.Nack`. You can read more at the "Deadlines" section near the top of https://godoc.org/cloud.google.com/go/pubsub.

If I had to guess, I would say a delay in your application's processing (perhaps due to CPU starvation or increased network latency) prevented your application from acking messages as quickly as it normally does, which caused our client to extend the deadlines of those messages.

**Comment by Tang8330** [comment] 2017-05-16 22:11
Thanks so much Jonathan for the detailed explanation!

I am currently investigating this with Kir and Kamal, as my application process time (max/avg) was about 15/2.5 seconds. The ack deadline was set to 300 seconds, and we were still seeing a huge load on `mod_ack_deadline`

Do you think it is possible that pub/sub servers were having issues, and as a result, this problem came up? The timespan for this is `5/5 6 pm - 5/5 9 pm (PST)` 

As a side note -
I have done a pretty thorough analysis on my end via stackdriver, and would love to share the findings with you -- could you share your email address with me?

**Comment by danoscarmike** [comment] 2017-06-27 19:38
@Tang8330 have had a chance to investigate this with backend team?  Are P0 and bug labels still appropriate/relevant to the client?  Thanks!

**Comment by jba** [comment] 2017-08-08 18:17
Closing this due to lack of activity. Reopen if necessary.

**Comment by karlmutch** [comment] 2017-08-11 02:22
Hi,  I have tried to locate the ModifyAckDeadline inside the public Go APIs but it does not appear to be defined, at least on the godoc and the code I have been reading.  It is certainly there inside the package as a private method. How do I get access to this method as I cannot use the default max extension, I don't have this knowledge until I get my messages from pubsub?

**Comment by jba** [comment] 2017-08-11 14:03
I'm sorry, I closed this because I thought your issue had been resolved on the email thread and we hadn't heard back from you. 

This client (cloud.google.com/go/pubsub) doesn't provide a way for users to call ModifyAckDeadline themselves. We don't plan on exposing that functionality. You can always use the lower-level client at cloud.google.com/go/pubsub/apiv1 for full control.

> I cannot use the default max extension, I don't have this knowledge until I get my messages from pubsub

So you're saying that each message has a variable amount of time it will take to process, which you can't know until you've seen the message, and you want control over when that message will be released so that another subscriber can claim it. 

For instance, maybe the time to process a message is proportional to its size. Once you know a message's size, you can estimate the time it will take. You want to extend the deadline up to that time (or maybe, to be generous, 2x that time or something like that), but if it takes longer, then you want to release the message. 

I think you can accomplish that with this client like so:
1. Set MaxExtension to something very large, like a year.
2. When you receive a message, start processing it, but also set a timer that will expire at twice the estimated processing time for that message.
3. When you're done processing a message, ack it and stop the timer.
4. If the timer finishes first, nack the message.

**Comment by karlmutch** [comment] 2017-08-11 14:59
The suggested approach would not be able to handle the use case of the
machine processing the message going down or a software panic which is what
I believe the feature was designed for.

This method is exposed in other language bindings such as python. Is there
a reason or risk with pubsub for not exposing it that I should take into
consideration ?

I will look at the lower level API however it would imply an expensive
rewrite sadly.

Thanks
Karl

**Comment by jba** [comment] 2017-08-11 15:17
If the process handling the message goes down, then the message will no longer have its deadline extended, so it will get released for re-delivery fairly quickly. The maximum time before the message is released is the subscription's ack deadline, defaulting to 10 seconds.

The rationale for not exposing this and other low-level features of the pubsub API is that we're trying to build a client that is easy to use but provides high throughput by default.

@karlmutch I realize now that you're not the OP, so ignore my comment about not hearing back from you on the email thread. I hope now we're both less confused :)

Please explain your use case and what's not working for you, and we'll try to help. (This is my last day before a one-week vacation, so we may have to continue the discussion later.)

**Comment by karlmutch** [comment] 2017-08-11 15:40
Thanks for the additional detail.  I believe I am now less confused.  I
think I got myself confused reading the deadline section of the docs,
https://godoc.org/cloud.google.com/go/pubsub, in combination with the
suggestion earlier in the message chain, prior to us talking, that I would
need to manually extend the deadline myself.  I just need to set the
maximum and then let the background go routine processing provided by the
API doing the extensions on my behalf.  If the process, or machine dies
then the automatic extension would not occur and the message would be
requeued by the google platform after 10 seconds.

Thanks, I think it is cleared up.

**Closed** 2017-08-11 16:21 UTC
Labels: bug, P0, pubsub
