### ISSUE TITLE
topic.IAM().TestPermissions always fail with rpc error when called immediately after NewClient.

### ISSUE THREAD

**Issue by 80nashi** [GoogleCloudPlatform/google-cloud-go#713] opened 2017-08-01 00:07 UTC
The following code snippet always fails with "TestPermissions failed: rpc error: code = Unavailable desc = there is no address available".

```
package main

import (
        "log"

        // Imports the Google Cloud Pub/Sub client package.
        "cloud.google.com/go/pubsub"
        "golang.org/x/net/context"
)

func main() {
        ctx := context.Background()

        // Sets your Google Cloud Platform project ID.
        projectID := "project-does-not-matter"

        // Creates a client.
        client, err := pubsub.NewClient(ctx, projectID)
        if err != nil {
                log.Fatalf("Failed to create client: %v", err)
        }

        topic := client.Topic("topic-does-not-matter-either")
        perms, err := topic.IAM().TestPermissions(ctx, []string{
                "pubsub.topics.publish",
                "pubsub.topics.update",
        })
        if err != nil {
                log.Fatalf("TestPermissions failed: %v", err)
        }
        for _, perm := range perms {
                log.Printf("Allowed: %v", perm)
        }
}

```

When NewClient is called with the blocking option (`client, err := pubsub.NewClient(ctx, proj, option.WithGRPCDialOption(grpc.WithBlock()))
`), it works.  See PR https://github.com/GoogleCloudPlatform/golang-samples/pull/282 for example.

**Comment by pongad** [comment] 2017-08-09 04:01
This issue seems to be a problem with grpc, not the client library. I created an issue for this at grpc-go (linked above), with a slightly smaller reproduction and some findings. Let's move further discussions there?

I'll close this issue for now. Please reopen if you think the issue belongs here.

**Closed by pongad** 2017-08-09 04:01 UTC
Labels: bug, P1, pubsub
