### ISSUE TITLE
firestore querying nil fails if attribute does not exist

### ISSUE THREAD

**Issue by asontha** [GoogleCloudPlatform/google-cloud-go#1133] opened 2018-09-03 22:31 UTC
## Client

Firestore

## Describe Your Environment

local development

## Expected Behavior

when querying for documents where attribute does not exist, this should work:
.Where(<attribute we're looking for>, "==", nil)

## Actual Behavior

Requires that the attribute exists but is set to null

**Comment by jadekler** [comment] 2018-09-04 14:46
Could you point to the documentation for that property? Or, are you seeing this behavior in other languages?

**Comment by jba** [comment] 2018-09-04 16:45
@schmidt-sebastian, what is the right behavior here?

**Comment by schmidt-sebastian** [comment] 2018-09-04 16:53
`Nil/Null` are special field values in Firestore that are distinct from "field is not set". You can only query for fields that are explicitly set to `nil`.

Note that there is a work-around that might help here. You can use `orderBy` to only return documents that have an explicit value for a given field, no matter what the value is. While this is the opposite of what you are asking for, it might solve your problem nonetheless.

**Comment by jadekler** [comment] 2018-09-04 17:16
Closing since this seems to be working as intended.

**Closed by jadekler** 2018-09-04 17:16 UTC
Labels: needs more info, triage me
