### ISSUE TITLE
missing root certs cause pubsub.NewClient to fail silently and wait forever

### ISSUE THREAD

**Issue by groob** [GoogleCloudPlatform/google-cloud-go#790] opened 2017-10-13 03:17 UTC
If system roots are missing, `pubsub.NewClient` will fail but block forever and never return an error.

To reproduce, create a alpine dockerfile without system roots:

```
FROM alpine

COPY ./creds.json /credentials.json
ENV GOOGLE_APPLICATION_CREDENTIALS /credentials.json
COPY ./dial /dial


CMD ["/dial"]
```

Where `dial` looks like:
```
func main() {
	_, err := pubsub.NewClient(context.Background(), "my-project")
	if err != nil {
		panic(err)
	}
        fmt.Println("done")
}
```

```
GOOS=linux CGO_ENABLED=0 go build -o dial && docker build -t dial . && docker run -it --rm dial
```

I was initially going to file this bug with grpc, because it's triggered inside `grpc.DialContext`, but it appears to be caused by `			option.WithGRPCConnectionPool(runtime.GOMAXPROCS(0)),` in pubsub.NewClient. Removing this line https://github.com/GoogleCloudPlatform/google-cloud-go/blob/d4d264c39efbd1c3bf7e55862de20cfe0f851952/pubsub/pubsub.go#L66

causes the binary to fail with the actual error. 
```
panic: constructing pubsub client: x509: failed to load system roots and no roots provided
```

The actual error within grpc happens here https://github.com/grpc/grpc-go/blob/c209cdff16049a924bef4aa5c6f7588f0b42b2fa/clientconn.go#L695-L696 but the balancer implementations appears to ignore it somewhere.

**Comment by pongad** [comment] 2017-10-23 05:13
I suspect this is caused by gRPC issue with Balancer. @menghanl WDYT?

**Comment by menghanl** [comment] 2017-10-23 21:35
Yes, I think it's caused by the balancer change.
Now, there will always be a balancer in the gRPC client (pickfirst is the default if no custom balancer is specified).
The ClientConn doesn't know the reason the client failed because balancer is managing the connections. And currently, balancers see credentials errors as transient errors.

We could possibly do something on this. It would make balancer more complex, and make it tricky to implement a custom balancer.

How bad would it be if we keep the current behavior that gRPC dial doesn't fail on this error (blocking dial fails with timeout, not creds errors), and the errors are written to logs?

**Comment by jba** [comment] 2017-12-18 13:55
Closing because (1) this is a gRPC issue, not one related to code in this repo, and (2) there are no objections to the proposed workaround (add a timeout to Dial, and check the logs).

**Closed by jba** 2017-12-18 13:55 UTC
Labels: api: pubsub, priority: p1, type: bug
