### ISSUE TITLE
pubsub: Receive doesn't call the callback function upon new unacknowledged messages

### ISSUE THREAD

**Issue by aseure** [GoogleCloudPlatform/google-cloud-go#740] opened 2017-08-25 16:23 UTC
Version: `v0.12.0`

We have discovered that one of our Go programs, which should consume ~800 messages once every hour, is not correctly receiving the Pubsub messages that should have been sent by the callback function passed to the `Receive`. At startup, it will correctly get the messages already available and unacknowledged. However, one hour later, when the ~800 new messages arrive, nothing happens. By restarting a new instance, it works again and will block the hour after with the new messages, etc.

By adding debug `Print*` statements, we discovered that it's actually blocked at [this `select` from `iterator.go`](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/v0.12.0/pubsub/iterator.go#L92).

What could be the issue?

**Comment by jba** [comment] 2017-08-25 16:33
Please roll back to v0.11.0 while we investigate.

**Comment by aseure** [comment] 2017-08-25 19:13
Rolling back to `v0.11.0`, seems to have fixed the issue: two consecutive hours of messages have been processed. I'll let it run for a few more hours to make sure it's working. If so, I'll try to `git bisect` between `v0.11.0` and `v0.12.0` and keep you updated.

Thank you for the quick answer.

**Comment by jba** [comment] 2017-08-25 19:30
Unless it gives you pleasure, I wouldn't worry about the git bisect. It's almost certainly the change from Pull to StreamingPull that causes this. I will try to reproduce.

**Comment by jba** [comment] 2017-08-28 13:40
I suspect there is some network issue that is disconnecting your stream, and the client is not properly recovering from that. But I can't reproduce. I ran [this program](https://gist.github.com/jba/99879125dfe20bc62a1d82b47c89b730) over the weekend. I published 800 messages at 1-hour intervals and received them in a separate process. I also tried a 2-hour interval. In both cases  I was still receiving messages after many hours.

My 2-hour run looked like:
```
> go run pubsub.go publish -project MY-PROJECT-ID -topic test-topic -count 800 -interval 2h
```
and in another shell:
```
go run pubsub.go receive -project MY-PROJECT-ID -topic test-topic -sub test-sub -interval 2h
```

Can you try to reproduce with my code? Also, I would like to see if any errors are being returned from the low-level stream calls. Maybe you could instrument your system to log them? The relevant places in the v0.12.0 code are:
- https://code.googlesource.com/gocloud/+/v0.12.0/pubsub/service.go#392
- https://code.googlesource.com/gocloud/+/v0.12.0/pubsub/service.go#462
- https://code.googlesource.com/gocloud/+/v0.12.0/pubsub/service.go#477

Thanks in advance for your help.

**Comment by yanickbelanger** [comment] 2017-08-30 12:37
It looks like we also get the error with our setup: one of our GKE container stop receiving pubsub message after a while, and a restart of the container resume the message processing, until it stops again. We suspected that the `receive` function returned with no error, but it does not, it just stops receiving message. We will probably rollback to the previous version of the client.

**Comment by jba** [comment] 2017-08-30 16:32
@yanickbelanger It would be great if you could log the low-level Send and Recv calls as I described above.

**Comment by yanickbelanger** [comment] 2017-08-31 13:05
@jba I've just pushed on our cluster a test service that has some fmt.printf around the line you mentioned above. It should receive a message every minutes from another service. We'll see how it goes.

**Comment by yanickbelanger** [comment] 2017-09-01 11:55
We cannot reproduce the issue in our test. We suspect the relatively short interval between the test messages may prevent our service to reach the conditions leading to the issue. We've added a subscription to another topic that publishes messages every 60-180 minutes, will report back later.

BTW, it's probaly normal, but even if our test went well, we still see errors from the logs I've added as you suggested above:
- `*status.statusError, rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR`
- `*status.statusError, rpc error: code = Unavailable desc = The service was unable to fulfill your request. Please try again. [code=8a75]`
- `*status.statusError, rpc error: code = Unavailable desc = transport is closing`

**Comment by dansiemon** [comment] 2017-09-01 19:40
I see the same with a service that pulls from many subscriptions. The ones with frequent messages keep going fine but the subscriptions that only have messages every ~15 minutes stop receiving after they initially drain the queue.

**Comment by yanickbelanger** [comment] 2017-09-02 00:55
We've seen the issue with our last test. The service received successfully few messages withing a couple of hours, then stop receiving the next messages. Once restarted, the service processed the pending messages. Between the last received message and the service restart, we got the following logs (added in `service.go` after our discussion above):

```
--- Streaming pull send (send) begin for projects/[project]/subscriptions/[subscription]
--- !!! Streaming pull recv (fetchMessages) error for projects/[project]/subscriptions/[subscription]: *status.statusError, rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR
--- Streaming pull send (openLocked) for projects/[project]/subscriptions/[subscription]
--- Streaming pull recv (fetchMessages) for projects/[project]/subscriptions/[subscription]
--- !!! Streaming pull recv (fetchMessages) error for projects/[project]/subscriptions/[subscription]: *status.statusError, rpc error: code = Unavailable desc = The service was unable to fulfill your request. Please try again. [code=8a75]
--- Streaming pull send (openLocked) for projects/[project]/subscriptions/[subscription]
--- Streaming pull recv (fetchMessages) for projects/[project]/subscriptions/[subscription]
```

**Comment by pongad** [comment] 2017-09-02 01:01
@yanickbelanger Just to make sure I understand the logs correctly, are the sends and recvs succeeding? Or is it that the sends and recvs themselves never return?

**Comment by pongad** [comment] 2017-09-02 01:26
@jba I *think* I know what's going on. On L427 we unlock before Send or Recv so that both can happen at the same time. gRPC allows one Send and one Recv to happen concurrently, but not multiple Sends or multiple Recvs. This is usually OK, since each stream only has one goroutine pulling messages and one sending acks.

Looking at the logs, I think it's possible that a Recv fails, so we attempt to reopen the stream (L433). But reopening a stream causes a Send (L392). Now we have two Sends, one from reopening and one from acking. The two can happen concurrently since the latter is out of lock.

Please let me know if you think I'm on the right track.

**Comment by pongad** [comment] 2017-09-04 08:28
I bring good news! I'm finally able to to repro.
@jba I reproed this by your test program, but I had to run the receiver side on a GCE instance. Perhaps there's something about google internal network that prevents this from triggering...?

I modified `fetchMessages` like this:
```go
	log.Println("fetch calling")
	err := p.call(func(spc pb.Subscriber_StreamingPullClient) error {
		var err error
		log.Println("inner fetch calling")
		res, err = spc.Recv()
		log.Println("inner fetch returned", res, err)
		return err
	})
	log.Println("fetch returned", err)
```
and modified `send` similarly.

I made the publishing half publish 2 messages every 15 minutes. I got these logs:
```
2017/09/04 07:53:36 fetch calling
2017/09/04 07:53:36 inner fetch calling
2017/09/04 07:53:46 received 0 messages
2017/09/04 07:53:49 inner fetch returned (messages elided)  <nil>
2017/09/04 07:53:49 fetch returned <nil>
2017/09/04 07:53:49 fetch calling
2017/09/04 07:53:49 inner fetch calling
2017/09/04 07:53:49 send calling
2017/09/04 07:53:49 inner send calling (ack IDs elided)
2017/09/04 07:53:49 inner send returned <nil>
2017/09/04 07:53:49 send returned <nil>
2017/09/04 07:58:46 received 2 messages
2017/09/04 08:03:46 received 2 messages
2017/09/04 08:08:46 received 2 messages
2017/09/04 08:13:46 received 2 messages
2017/09/04 08:18:46 received 2 messages
```

The call to `spc.Recv` simply never returns. I *suspect* that this is a bug in gRPC. I used gRPC v1.5.0 for testing. Tomorrow, I'll test it again with v1.6.0 to see.

@yanickbelanger @dansiemon Could you let us know which gRPC version you're on?

**Comment by dansiemon** [comment] 2017-09-05 00:50
Yes, I was running in GCE (GKE) w/ gRPC 1.6.

**Comment by pongad** [comment] 2017-09-05 09:01
I can repro this in both Go and Java using only gRPC-generated code. I think the root cause of this is probably on the server and not the client especially because Java and Go have different gRPC implementations.

@jba I'll open an internal bug for this and CC you

**Comment by yanickbelanger** [comment] 2017-09-05 11:11
@pongad Yes I'm running on GKE.

**Comment by jonbretman** [comment] 2017-09-07 10:16
@pongad what is the best way to track progress of the internal bug?

**Comment by jba** [comment] 2017-09-07 10:25
We'll update this issue when we have more information.

**Comment by purohit** [comment] 2017-09-15 16:11
I inadvertently updated to `v0.12.0` as well and we received the same problem, although our queue backpressure was much greater (30,000+ messages). I've rolled back to `v0.11.0` as suggested and we will see if the problem gets resolved long term.

**Comment by junghoahnsc** [comment] 2017-09-18 18:12
We had the exact same issue in our production.
After we upgraded to `v0.12.0`, the streaming pulling from a subscription that has a periodic publishing stopped after one or two bulk pullings. However the pulling from subscriptions that have a continuous publishing works well. `v0.11.0` works fine in both cases now.

**Closed** 2017-09-21 05:59 UTC
Labels: bug, P0, pubsub
