### ISSUE TITLE
Bigquery latency issue

### ISSUE THREAD

**Issue by arriqaaq** [GoogleCloudPlatform/google-cloud-go#955] opened 2018-04-03 09:06 UTC
## Client
BigQuery Go Client

## Describe Your Environment
Ubuntu 14
## Expected Behavior
BigQuery client Put method should send messages fast, with only network delay( and encoding/decoding of ValueStructs) variance taken into account.

## Actual Behavior

method newInsertRequest slows down with time. 
I have been using this client for streaming data into bigquery from kafka. Usually I have to restart the clients few times in a day, when I benchmarked this library, this particular method newInsertRequest does not perform well. I understand it depends on my schema, but this function's performance degrades with time to a point where it takes 2-10 times the network time. Surprising thing is if i restart this client, this function works pretty fast. Could you please write test case to test this function? It's causing the bigquery client to not function properly. I've testes this against a collection of random messages of nearly 15-18kb in size. Performance degrades linearly

**Comment by jadekler** [comment] 2018-04-03 16:37
Hi @arriqaaq, I wrote a [small program to test your question](https://gist.github.com/jadekler/e855352a816daad8f42d171e08202773) and was unable to replicate the results you're describing:

![screen shot 2018-04-03 at 9 34 25 am](https://user-images.githubusercontent.com/3584893/38262550-5cf77eda-3722-11e8-9688-fb5966d8001c.png)

(times in ns)

Could you tell me more about your program - is there processing happening around the put? Also, I recommend putting some opencensus or even `time.Now()` / `time.Since()` benchmarking in your app - it may give us clues as to what's going on.

**Comment by arriqaaq** [comment] 2018-04-04 22:13
Hi @jadekler 

Thanks for the quick response
My program is a consumer from kafka which processes messages and puts them into bigquery. I've timed the Put method by using time.Now()/time.Since()
The problem arises because my messages are 15-20 KB in size, which translates to a bigger struct of multiple data types. I send these messages in a batch of 1000 items per second.

Could you let me know what sort of data I can provide which could be helpful to you?

Would really appreciate your help on this

**Comment by jadekler** [comment] 2018-04-05 01:34
@arriqaaq Ahh ok. Could you provide me a snippet of your code? I'm interested in seeing the `start := time.Now()` and `time.Now().Sub(start)` and all code between (including the Put call).

**Comment by jadekler** [comment] 2018-04-06 15:36
Thanks @arriqaaq, we'll investigate.

**Comment by jadekler** [comment] 2018-04-10 22:59
Hi @arriqaaq. So I ran some more tests. I first tried that same [simple bigquery uploader](https://gist.github.com/jadekler/e855352a816daad8f42d171e08202773), but this time with 32kb data per insert. Unfortunately although this slowed things down, the performance was still uniform.

I then tried [making the app highly concurrent (spin up a goroutine per Put call)](https://gist.github.com/jadekler/ae2e6ed44a358f164271a6a13e1b0e3d), and I observed a linear increase in time as you mentioned.

![screen shot 2018-04-10 at 3 57 51 pm](https://user-images.githubusercontent.com/3584893/38587894-0a7ca390-3cd8-11e8-8bc2-3b0131401655.png)

Is that what you're doing - spinning up goroutines for each Put call? If not, could I ask you to provide a reproduction of your problem that we could run? Perhaps in a [gist](gist.github.com), or a small github repo?

**Comment by arriqaaq** [comment] 2018-04-13 09:36
Though could you explain why mutliple put calls in goroutines increase linearly with time? I run multiple consumers on one instance, so that is the closest I get to running multiple goroutines, one for each consumer group instance

**Comment by arriqaaq** [comment] 2018-04-13 10:54
Here is a flame graph, in case it helps

https://gist.github.com/arriqaaq/98cb787b488aca5808ea535a41f9006f

**Comment by jadekler** [comment] 2018-04-16 16:42
@arriqaaq Thanks, I appreciate it. As to why goroutines cause a linear growth in time; resource exhaustion. Just running into the limit of can do per second, which causes a backup of work.

**Comment by jadekler** [comment] 2018-04-19 14:51
Hi @arriqaaq 

> I will try to provide a gist with some dataset to reproduce this problem

Per the above, I was hoping you'd be able to provide us with a runnable reproduction. Apart from the concurrent example above, I was unable to reproduce your results. Would that be possible for you?

**Comment by jadekler** [comment] 2018-04-19 14:52
Hi @arriqaaq 

> I will try to provide a gist with some dataset to reproduce this problem

Per the above, I was hoping you'd be able to provide us with a runnable reproduction. Apart from the concurrent example above, I was unable to reproduce your results. Would that be possible for you?

**Comment by arriqaaq** [comment] 2018-04-20 13:29
Hey @jadekler 

I thought the flame graph would help. As you can see, the test results will remain consistent for you if you are going to use the same struct with values, replicated n number of times because of the fieldCache variable, as pointed out in the flame graph too. If you keep producing random data, you will observer the lag.

**Comment by jadekler** [comment] 2018-04-23 03:44
@arriqaaq It is useful, but I think a repro would be the best way for us to debug this since we're unable to reproduce it ourselves.

**Comment by jba** [comment] 2018-06-08 10:12
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Closed by jba** 2018-06-08 10:12 UTC
Labels: :rotating_light:, api: bigquery, priority: p1, triage me, type: bug
