### ISSUE TITLE
go get -u cloud.google.com/go/ fails "unrecognized import path "cloud.google.com/go""

### ISSUE THREAD

**Issue by macrael** [GoogleCloudPlatform/google-cloud-go#820] opened 2017-12-04 23:02 UTC
It appears that the website cloud.google.com/go has been taken down. 

I can't build my projects because an import for "cloud.google.com/go" doesn't download anything. The site https://cloud.google.com/go no longer has the required meta tag to point to the repo. 

Please resolve this, my build process is broken right now.

**Comment by elithrar** [comment] 2017-12-04 23:05
As a fellow user:

go get -v -u cloud.google.com/go
Fetching https://cloud.google.com/go?go-get=1
Parsing meta tags from https://cloud.google.com/go?go-get=1 (status code
200)
cloud.google.com/go (download)

Is there an intermediate proxy that might be interfering?

**Comment by macrael** [comment] 2017-12-04 23:10
$ go get -v -u cloud.google.com/go
Fetching https://cloud.google.com/go?go-get=1
Parsing meta tags from https://cloud.google.com/go?go-get=1 (status code 200)
package cloud.google.com/go: unrecognized import path "cloud.google.com/go" (parse https://cloud.google.com/go?go-get=1: no go-import meta tags ())

**Comment by macrael** [comment] 2017-12-04 23:10
that site was 404 for me for a minute, and when I grep through the page returned currently I don't see any meta tags.

**Comment by timfallmk** [comment] 2017-12-05 00:02
I've confirmed that the problem appears to be missing go import tags: From `golang.org`:

```shell
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="golang.org/x/net git https://go.googlesource.com/net">
<meta name="go-source" content="golang.org/x/net https://github.com/golang/net/ https://github.com/golang/net/tree/master{/dir} https://github.com/golang/net/blob/master{/dir}/{file}#L{line}">
<meta http-equiv="refresh" content="0; url=https://godoc.org/golang.org/x/net">
</head>
```

Equivalent section on `cloud.google.com/go` (with forwarding) shows no `go` related tags.

**Comment by bradfitz** [comment] 2017-12-05 00:07
Hey @broady, this is bad. Please escalate.

Looks like the URL path canonicalization (`GET /go/bigtable?go-get=1` => `/go/bigtable/?go-get=1`) is happening before the `go-get=1` special-casing.

**Comment by dfawley** [comment] 2017-12-05 00:08
FWIW, I filed an internal bug about this.

**Comment by ankurcha** [comment] 2017-12-05 00:09
And this is why we should vendor the internet before building software?

**Comment by timfallmk** [comment] 2017-12-05 00:10
@ankurcha Also breaks vendoring:

```shell
dep ensure -v --vendor-only
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export cloud.google.com/go: unable to deduce repository and source type for "cloud.google.com/go": unable to read metadata: go-import metadata not found
```

I appreciate your snark, but even that breaks ;)

**Comment by bradfitz** [comment] 2017-12-05 00:16
@timfallmk, it breaks updating vendored deps, but not people who've already vendored their deps and just want to hack on & rebuild their own code.

**Comment by ankurcha** [comment] 2017-12-05 00:16
Sorry didn't mean to be snarky. Just spent a good half an hour trying to figure out what broke my day long roll. :-/ 

Actually, I also noticed it when my `dep ensure --vendor-only` step broke

**Comment by timfallmk** [comment] 2017-12-05 00:18
@bradfitz Fair enough. It's a fine distinction. Unfortunately, it also breaks (at least for `dep`) when _checking_ to see if vendored dependencies _should_ be updated. Your point is well taken however.

**Comment by chetananand** [comment] 2017-12-05 00:26
If someone is using glide for vendoring, then adding something like:
```
package: cloud.google.com/go
vcs: git
repo: https://code.googlesource.com/gocloud
subpackages:
  - compute/metadata
  - internal/version
```
will help as a temporary workaround.

**Comment by jba** [comment] 2017-12-05 00:28
We've found the problem and are working on a solution.

**Comment by jba** [comment] 2017-12-05 00:33
This should be fixed. Ping this issue if it's still a problem.

**Closed by jba** 2017-12-05 00:33 UTC

**Comment by macrael** [comment] 2017-12-05 01:28
Thanks all!

**Comment by scottpettyjohn** [comment] 2018-11-20 16:49
I am having the same issue described.
go get -v -u cloud.google.com/go
Fetching https://cloud.google.com/go?go-get=1
https fetch failed: Get https://cloud.google.com/go?go-get=1: x509: certificate signed by unknown authority
package cloud.google.com/go: unrecognized import path "cloud.google.com/go" (https fetch: Get https://cloud.google.com/go?go-get=1: x509: certificate signed by unknown authority)

If I use the -insecure flag, I get the missing meta-tag:

go get -v -u -insecure cloud.google.com/go/...
Fetching https://cloud.google.com/go?go-get=1
https fetch failed: Get https://cloud.google.com/go?go-get=1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Fetching http://cloud.google.com/go?go-get=1
Parsing meta tags from http://cloud.google.com/go?go-get=1 (status code 401)
package cloud.google.com/go/...: unrecognized import path "cloud.google.com/go/..." (parse http://cloud.google.com/go?go-get=1: no go-import meta tags ())

**Comment by bradfitz** [comment] 2018-11-20 18:03
@scottpettyjohn, looks like you're having a different problem. Also, this issue is closed and almost a year old.

Can you file a new bug. We don't track old closed bugs.

You might be missing a ca-certificates package or something, but you should include details about your OS & version in a new bug you file (not here).

**Comment by Ark-kun** [comment] 2020-01-31 23:13
Having this again:
```
go: cloud.google.com/go@v0.44.3: unrecognized import path "cloud.google.com/go" (parse https://cloud.google.com/go?go-get=1: no go-import meta tags ())
```

**Comment by tbpg** [comment] 2020-02-03 20:21
Thank you for the report. Unfortunately, I'm not seeing the error right now.

Do you have a proxy enabled? That would sidestep this issue in the future.

```
$ go env GOPROXY
https://proxy.golang.org,direct
```

**Comment by broady** [comment] 2020-02-03 20:25
Locking this issue. If you see something similar, please open a new bug.
