### ISSUE TITLE
Table.exists hangs

### ISSUE THREAD

**Issue by talonx** [GoogleCloudPlatform/google-cloud-go#805] opened 2017-11-11 14:28 UTC
I've a Bigtable client that connects to a local emulator. Lately it has started hanging on table.exists - the only thing that was updated recently was the emulator itself via apt. A thread dump reveals (client class names snipped at the bottom)
```
"main" #1 prio=5 os_prio=0 tid=0x00007ff678010000 nid=0x67c2 waiting on condition [0x00007ff67f143000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007441b7ad0> (a com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation$GrpcFuture)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:469)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.getBlockingResult(AbstractRetryingOperation.java:293)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.readFlatRowsList(BigtableDataGrpcClient.java:327)
	at com.google.cloud.bigtable.hbase.BigtableTable.getResults(BigtableTable.java:257)
	at com.google.cloud.bigtable.hbase.BigtableTable.exists(BigtableTable.java:166)
..........
```
Subsequent thread dumps taken at 30 second intervals reveals the the thread is stuck at the same place. 

After about 12 minutes, I get the following error - 
```
java.io.IOException: Failed to perform operation. Operation='checkAndMutate', projectId='emulator', tableName='mquery', rowKey='149de7d2-272b-4524-ace3-8d977da6faf6#27c893ee-b50c-4b47-b08f-f3824291a62a'
	at com.google.cloud.bigtable.hbase.BigtableTable.logAndCreateIOException(BigtableTable.java:522)
	at com.google.cloud.bigtable.hbase.BigtableTable.checkAndMutate(BigtableTable.java:470)
----snipped----
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 359999872003ns
	at io.grpc.Status.asRuntimeException(Status.java:517)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.getBlockingResult(AbstractRetryingOperation.java:300)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.checkAndMutateRow(BigtableDataGrpcClient.java:267)
	at com.google.cloud.bigtable.hbase.BigtableTable.checkAndMutate(BigtableTable.java:467)
	... 32 common frames omitted

```
This happens for each call. The 12-minute interval occurs in each case. It's brought my development to a grinding halt since I cannot use HBase/Bigtable at all. It was temporarily resolved by switching back to an older version of the emulator (gcloud 175 and 169) but the problem is back again today.

I've tried rolling back the pubsub library (another dependency in my project) from 0.26 to 0.24 since it has a dependency on grpc, but to no avail. The pubsub upgrade was done a few weeks ago to get around https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2569

Library versions:
google-cloud-core 1.8.0, 
google-cloud-core-grpc 1.8.0, 
google-cloud-core 1.8.0, 
bigtable-hbase-1.x 1.0.0-pre3

gcloud version output:
Google Cloud SDK 177.0.0
alpha 2017.10.20
beta 2017.10.20
bigtable 
bq 2.0.27
cbt 
core 2017.10.20
gsutil 4.28
pubsub-emulator 2017.10.20

OS: Ubuntu 17.10

java -version output: 
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by garye** [comment] 2017-11-11 14:56
Does anything hang if you skip the table.exists call?

**Comment by garye** [comment] 2017-11-11 18:00
You also might want to try building the emulator from source (this repository) and seeing if it exhibits the same behavior as the gcloud version.

Build this repo and run `bigtable/cmd/emulator/cbtemulator`.

Finally, if you can construct a simple, reproducible test case for us to look at that would help a lot.

**Comment by talonx** [comment] 2017-11-13 15:47
>>Does anything hang if you skip the table.exists call? 
I'll try this.

I've been running with the emulator from the source code, and it shows different results with different versions of the libraries (but stops eventually). I'll try to get a proper, reproducible test case.

**Comment by sduskis** [comment] 2018-06-05 14:17
I'm going to close this since we didn't get a reproducible test case.  Please feel free to reopen once we do.

**Closed by sduskis** 2018-06-05 14:17 UTC
Labels: api: bigtable, priority: p2, type: bug

**Comment by talonx** [comment] 2021-02-02 02:29
@JustinBeckwith What action is required from me here? The issue was closed in 2017.

**Comment by JustinBeckwith** [comment] 2021-02-02 02:42
None required - apologies for the noise!
