### ISSUE TITLE
storage: Large files are not being downloaded, API error 3 (urlfetch: UNSPECIFIED_ERROR))

### ISSUE THREAD

**Issue by ribice** [GoogleCloudPlatform/google-cloud-go#950] opened 2018-03-28 14:00 UTC
## Client

storage 

## Describe Your Environment

App Engine Standard Environment

## Expected Behavior

Objects gets downloaded

## Actual Behavior

We are using a 3rd party service for our reporting feature. In short, every night a file containing data from datastore for the last 24 hours is uploaded to GCS, in JSON format.

The problem is, if the file is larger than \~35MB the download fails with error: 'Get URL/~.json: API error 3 (urlfetch: UNSPECIFIED_ERROR))'

I tried creating a retry mechanism, but it fails every time. The code that retrieves file from GCS:

```
client, err := storage.NewClient(c)

if err != nil {
	return nil, err
}

bck := client.Bucket(bucketName[appID])

reader, err := bck.Object(path + "/~.json").NewReader(c)

if err != nil {
	return nil, err
}

defer reader.Close()

bts, err := ioutil.ReadAll(reader)

if err != nil {
	return nil, err
}

Manipulate bts
```

I searched for this error through web and in godoc/storage's documentation, but couldn't find anything meaningful.

**Comment by rogerhub** [comment] 2018-04-03 03:47
App Engine Standard has a [128MB memory limit](https://cloud.google.com/appengine/docs/standard/) in its default configuration. If you're downloading 35MB, maybe you're running into that? (I wouldn't be surprised if there were more than one copy of those bytes as they're coming in.) Although... that doesn't really explain the error message.

**Comment by ribice** [comment] 2018-04-05 08:47
I don't believe that this issue is related to memory limit.

Usually when there are memory limit issues, on stackdriver we see messages as:

`While handling this request, the process that handled this request was found to be using too much memory and was terminated. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may have a memory leak in your application.`

`Exceeded soft private memory limit of 256 MB with 338 MB after servicing 0 requests total`.

**Comment by jadekler** [comment] 2018-04-05 15:54
@ribice Just to clarify, is it uploading or downloading that's causing that error?

**Comment by ribice** [comment] 2018-04-05 15:56
Downloading.

**Comment by jadekler** [comment] 2018-04-05 16:03
👍 I think jba@ is intending to look at this issue (he's out until next week), but if I have some time today/tmr I will see if I can repro.

**Comment by rogerhub** [comment] 2018-04-06 04:28
I found https://cloud.google.com/appengine/docs/standard/python/outbound-requests#quotas_and_limits which states a 32MB limit for App Engine fetches. Maybe it's that?

**Comment by ribice** [comment] 2018-04-06 06:52
Might be that I guess. Should I try fetching a file from 'random' source larger than 32MB, using net/http to confirm this?

**Comment by jba** [comment] 2018-04-10 20:24
@ribice That would be a nice test.

You could also modify your code to use ranged reads, with (say) 20MB in each chunk. That could solve your problem.

**Comment by ribice** [comment] 2018-04-17 08:58
@jba Haven't had much time to test this. I did run a test (using the snippet below), but the request completed without errors.

```
req, err := http.NewRequest(“GET”, “http://ipv4.download.thinkbroadband.com/50MB.zip“, nil)
    if err != nil {
        log.Errorf(c, “Fail on creating request: %v”, err)
        return nil, err
    }
    client := urlfetch.Client(c)
    resp, err := client.Do(req)
    if err != nil {
        log.Errorf(c, “Fail on fetching file: %v”, err)
        return nil, err
    }
    _ = resp
```

Ranged reads will do the job for now. Ideally the error message should be more descriptive, not `API error 3 (urlfetch: UNSPECIFIED_ERROR))'`. 

I couldn't reproduce the error using urlfetch client.

**Comment by rogerhub** [comment] 2018-04-18 04:50
Does anything happen if you throw in a `ioutil.ReadAll(resp.Body)`?

**Comment by Dor1s** [comment] 2018-06-04 04:12
I have the same problem. For me that error happens during `NewReader()` call, i.e. even before any downloading.

**Comment by broady** [comment] 2018-08-01 23:44
@rogerhub it shouldn't; urlfetch actually performs the entire HTTP request, you don't get a real stream for the body back, it's essentially all in memory already.

@jba any update here? if not, please re-assign or downgrade to P2

**Comment by jba** [comment] 2018-08-02 21:56
I was able to reproduce this. `NewReader` returned the same error when a tried to read a large (39M) file.

Here's an example of how to use `NewRangeReader` to read a large file in pieces. This succeeded for me with chunk sizes up to 31M.
```
for offset := int64(0); true; offset += chunkSize {
    rr, err := obj.NewRangeReader(ctx, offset, chunkSize)
    if err != nil {
        if gerr, ok := err.(*googleapi.Error); ok && gerr.Code == 416 {
            // Assume "can't satisfy range" means we read everything.                                                                                                                                                 
            break
        }
        return err
    }
    defer rr.Close()
    bytes, err := ioutil.ReadAll(rr)
    if err != nil {
        return err
    }
}
```

Closing this bug, since this is not an issue with the storage client.

**Closed by jba** 2018-08-02 21:56 UTC
Labels: :rotating_light:, api: storage, priority: p1, type: bug
