### ISSUE TITLE
Traces for gRPC-only backends

### ISSUE THREAD

**Issue by anopheles** [GoogleCloudPlatform/google-cloud-go#456] opened 2016-12-09 16:13 UTC
I am currently developing a grpc backend and want to use the trace-api. Unfortunately, the trace client only offers methods for http-requests.

I found this interesting issue, but I'm not quite sure if it solves my problem https://github.com/GoogleCloudPlatform/google-cloud-go/pull/444

Is it possible to still upload custom traces with the trace api?

**Comment by ptone** [comment] 2016-12-10 00:12
this seems to be a duplicate of #412

**Comment by rakyll** [comment] 2016-12-16 20:41
Related CL: https://code-review.googlesource.com/#/c/9690/

I commented on the CL that we are going through a rewrite (towards #412), but it will take longer that we wished and we should consider enabling non-HTTP cases earlier.

//cc @jba

**Comment by pongad** [comment] 2017-08-10 05:37
It looks like this feature is already provided by [`GRPCServerInterceptor`](https://godoc.org/cloud.google.com/go/trace#Client.GRPCServerInterceptor) right? I think this issue can be closed, unless we want to keep it open until interceptor is stabilized?

**Comment by jba** [comment] 2017-12-11 20:53
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).

**Closed by jba** 2017-12-11 20:53 UTC
Labels: api: trace, type: feature request
