### ISSUE TITLE
storage: Client is leaking go routine(s).

### ISSUE THREAD

**Issue by Bplotka** [GoogleCloudPlatform/google-cloud-go#1025] opened 2018-06-06 15:33 UTC
Repro unit test:
```go
package gcs

import (
	"context"
	"os"
	"testing"
	"time"

	"cloud.google.com/go/storage"
	"github.com/fortytw2/leaktest"
	"github.com/stretchr/testify/require"
)

func TestBug(t *testing.T) {
	defer leaktest.CheckTimeout(t, 10*time.Second)()

	gcsClient, err := storage.NewClient(context.Background())
	require.NoError(t, err)

	testName := "test-gcs-leak"
	bkt := gcsClient.Bucket(testName)

	defer func() {
		if err := bkt.Delete(context.Background()); err != nil {
			t.Logf("deleting bucket failed: %s", err)
		}

		gcsClient.Close()
	}()

	require.NoError(t, bkt.Create(context.Background(), os.Getenv("GCP_PROJECT"), nil))
}
```
Basically I am unable to detect leaks easily on my own code if the client library leaks go routines on its own ):

I am pretty sure it is not limited to storage, but not tested any other client.

The truth is that it must be only some single go routine that is leaked, because long-term running applications that use this library does not indicate intensive mem usage or leak.

This is just annoying while testing my own code.

## Client

My vendoring stats:
```
[[projects]]
  name = "cloud.google.com/go"
  packages = [
    "compute/metadata",
    "iam",
    "internal",
    "internal/optional",
    "internal/version",
    "storage",
    "trace/apiv1"
  ]
  revision = "2d3a6656c17a60b0815b7e06ab0be04eacb6e613"
  version = "v0.16.0"
```

## Describe Your Environment

64bit Ubuntu

## Expected Behavior

Above unit test output that uses gcs storage client:
```
=== RUN   TestBug
--- FAIL: TestBug (10.03s)
	leaktest.go:90: leaktest: timed out checking goroutines
	leaktest.go:108: leaktest: leaked goroutine: goroutine 30 [IO wait]:
		internal/poll.runtime_pollWait(0x7f7fe08c3f00, 0x72, 0xc420542858)
			/usr/local/go/src/runtime/netpoll.go:173 +0x57
		internal/poll.(*pollDesc).wait(0xc42018a618, 0x72, 0xffffffffffffff00, 0xa19660, 0xc936e8)
			/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
		internal/poll.(*pollDesc).waitRead(0xc42018a618, 0xc420450000, 0x1000, 0x1000)
			/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
		internal/poll.(*FD).Read(0xc42018a600, 0xc420450000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
		net.(*netFD).Read(0xc42018a600, 0xc420450000, 0x1000, 0x1000, 0x435c09, 0xc420086900, 0x200000003)
			/usr/local/go/src/net/fd_unix.go:202 +0x4f
		net.(*conn).Read(0xc4201d02b0, 0xc420450000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:176 +0x6a
		crypto/tls.(*block).readFromUntil(0xc4201c5380, 0x7f7fe0883230, 0xc4201d02b0, 0x5, 0xc4201d02b0, 0xc420542a10)
			/usr/local/go/src/crypto/tls/conn.go:493 +0x96
		crypto/tls.(*Conn).readRecord(0xc4201d5180, 0x9daa17, 0xc4201d52a0, 0xc420086900)
			/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
		crypto/tls.(*Conn).Read(0xc4201d5180, 0xc4203b8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
		bufio.(*Reader).Read(0xc4201c9860, 0xc42033b458, 0x9, 0x9, 0xc4201d54b0, 0x61d060, 0xc4201d54b0)
			/usr/local/go/src/bufio/bufio.go:216 +0x238
		io.ReadAtLeast(0xa17880, 0xc4201c9860, 0xc42033b458, 0x9, 0x9, 0x9, 0x68a3e1, 0xc4201d5180, 0xc420451000)
			/usr/local/go/src/io/io.go:309 +0x86
		io.ReadFull(0xa17880, 0xc4201c9860, 0xc42033b458, 0x9, 0x9, 0x6d0c24, 0x7f7fe0883c90, 0xc4201d5180)
			/usr/local/go/src/io/io.go:327 +0x58
		net/http.http2readFrameHeader(0xc42033b458, 0x9, 0x9, 0xa17880, 0xc4201c9860, 0x0, 0xc400000000, 0x42c1e4, 0x9daac0)
			/usr/local/go/src/net/http/h2_bundle.go:1517 +0x7b
		net/http.(*http2Framer).ReadFrame(0xc42033b420, 0xc42037be60, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/http/h2_bundle.go:1775 +0xa4
		net/http.(*http2clientConnReadLoop).run(0xc420542fb8, 0x9da3c0, 0xc4203b7fb8)
			/usr/local/go/src/net/http/h2_bundle.go:8028 +0x90
		net/http.(*http2ClientConn).readLoop(0xc4202b7c00)
			/usr/local/go/src/net/http/h2_bundle.go:7956 +0x68
		created by net/http.(*http2Transport).newClientConn
			/usr/local/go/src/net/http/h2_bundle.go:7143 +0x65c
	leaktest.go:108: leaktest: leaked goroutine: goroutine 34 [IO wait]:
		internal/poll.runtime_pollWait(0x7f7fe08c3d60, 0x72, 0xc420543858)
			/usr/local/go/src/runtime/netpoll.go:173 +0x57
		internal/poll.(*pollDesc).wait(0xc4201f4a98, 0x72, 0xffffffffffffff00, 0xa19660, 0xc936e8)
			/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
		internal/poll.(*pollDesc).waitRead(0xc4201f4a98, 0xc4203b9000, 0x1000, 0x1000)
			/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
		internal/poll.(*FD).Read(0xc4201f4a80, 0xc4203b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
		net.(*netFD).Read(0xc4201f4a80, 0xc4203b9000, 0x1000, 0x1000, 0x435c09, 0xc420468780, 0x200000003)
			/usr/local/go/src/net/fd_unix.go:202 +0x4f
		net.(*conn).Read(0xc4201d0030, 0xc4203b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:176 +0x6a
		crypto/tls.(*block).readFromUntil(0xc42032c870, 0x7f7fe0883230, 0xc4201d0030, 0x5, 0xc4201d0030, 0xc420543a10)
			/usr/local/go/src/crypto/tls/conn.go:493 +0x96
		crypto/tls.(*Conn).readRecord(0xc4201d4700, 0x9daa17, 0xc4201d4820, 0xc420468780)
			/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
		crypto/tls.(*Conn).Read(0xc4201d4700, 0xc4202cf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
		bufio.(*Reader).Read(0xc4201c8600, 0xc4202cc738, 0x9, 0x9, 0xc4201d4a30, 0x61d060, 0xc4201d4a30)
			/usr/local/go/src/bufio/bufio.go:216 +0x238
		io.ReadAtLeast(0xa17880, 0xc4201c8600, 0xc4202cc738, 0x9, 0x9, 0x9, 0x68a3e1, 0xc4201d4700, 0xc4202ce000)
			/usr/local/go/src/io/io.go:309 +0x86
		io.ReadFull(0xa17880, 0xc4201c8600, 0xc4202cc738, 0x9, 0x9, 0x6d0c24, 0x7f7fe0883c90, 0xc4201d4700)
			/usr/local/go/src/io/io.go:327 +0x58
		net/http.http2readFrameHeader(0xc4202cc738, 0x9, 0x9, 0xa17880, 0xc4201c8600, 0x0, 0xc400000000, 0x42c1e4, 0x9daac0)
			/usr/local/go/src/net/http/h2_bundle.go:1517 +0x7b
		net/http.(*http2Framer).ReadFrame(0xc4202cc700, 0xc420305220, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/http/h2_bundle.go:1775 +0xa4
		net/http.(*http2clientConnReadLoop).run(0xc420543fb8, 0x9da3c0, 0xc4200497b8)
			/usr/local/go/src/net/http/h2_bundle.go:8028 +0x90
		net/http.(*http2ClientConn).readLoop(0xc4201e68c0)
			/usr/local/go/src/net/http/h2_bundle.go:7956 +0x68
		created by net/http.(*http2Transport).newClientConn
			/usr/local/go/src/net/http/h2_bundle.go:7143 +0x65c
FAIL
```

## Actual Behavior

Just pass, no leaktest stack traces.

I would really recommend using https://github.com/fortytw2/leaktest in every go project test. It will help detect these issues early on.

**Comment by Bplotka** [comment] 2018-06-06 16:09
I thought that context is not simply not cancelled, but actually, with explicit context cancel, leak output stays the same:
```go
package gcs

import (
	"context"
	"os"
	"testing"
	"time"

	"cloud.google.com/go/storage"
	"github.com/fortytw2/leaktest"
	"github.com/stretchr/testify/require"
)

func TestBug(t *testing.T) {
	defer leaktest.CheckTimeout(t, 10*time.Second)()

	ctx, cancel := context.WithCancel(context.Background())

	gcsClient, err := storage.NewClient(ctx)
	require.NoError(t, err)

	testName := "test-gcs-leak"
	bkt := gcsClient.Bucket(testName)

	defer func() {
		if err := bkt.Delete(ctx); err != nil {
			t.Logf("deleting bucket failed: %s", err)
		}

		gcsClient.Close()
		cancel()
	}()

	require.NoError(t, bkt.Create(ctx, os.Getenv("GCP_PROJECT"), nil))
}
```

**Comment by jadekler** [comment] 2018-06-06 17:15
Thanks for filing this. I looked into it - it appears to be an x/net/http2 bug. I've filed an issue - please track there. https://github.com/golang/go/issues/25759

(will re-open this issue if it turns out the above is incorrect, but it seems fairly straightforward)

**Comment by jadekler** [comment] 2018-06-07 17:02
Seems as though Go's h2 is working as intended. Re-opening to investigate more.

**Comment by jba** [comment] 2018-06-07 20:32
Try calling `http.DefaultTransport.CloseIdleConnections()` and see if that helps. If your leak checker allows you to ignore goroutines, you could also try that. (If not, I suggest finding one that does.)

It's hard for us to plumb the connection-closing logic through the clients, and not worth it given the above workarounds. If there are other downsides to those idle goroutines, we would reconsider.

**Closed by jba** 2018-06-07 20:32 UTC
Labels: api: storage, status: investigating

**Comment by Bplotka** [comment] 2018-06-08 06:10
`defer http.DefaultTransport.(*http.Transport).CloseIdleConnections()` while being bit sketchy (invoking some method on global variable, works fine. 

Also `storage` client accepts custom `http.Client` so all is fine:
```
package gcs

import (
	"context"
	"os"
	"testing"
	"time"

	"cloud.google.com/go/storage"
	"github.com/fortytw2/leaktest"
	"github.com/stretchr/testify/require"
	"net/http"
	"google.golang.org/api/option"
	"net"
)

func TestBug(t *testing.T) {
	defer leaktest.CheckTimeout(t, 10*time.Second)()

	c := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
			DialContext: (&net.Dialer{
				Timeout:   30 * time.Second,
				KeepAlive: 30 * time.Second,
				DualStack: true,
			}).DialContext,
			MaxIdleConns:          100,
			IdleConnTimeout:       90 * time.Second,
			TLSHandshakeTimeout:   10 * time.Second,
			ExpectContinueTimeout: 1 * time.Second,
		},
	}

	defer c.Transport.(*http.Transport).CloseIdleConnections()
	gcsClient, err := storage.NewClient(context.Background(), option.WithHTTPClient(c))
	require.NoError(t, err)

	testName := "test-gcs-leak"
	bkt := gcsClient.Bucket(testName)

	defer func() {
		if err := bkt.Delete(context.Background()); err != nil {
			t.Logf("deleting bucket failed: %s", err)
		}

		gcsClient.Close()
	}()

	require.NoError(t, bkt.Create(context.Background(), os.Getenv("GCP_PROJECT"), nil))
}
```
Thanks for so quick reaction! And sorry for filling issue that was not `storage` issue in any way ):

**Comment by jadekler** [comment] 2018-06-08 14:18
No worries - glad we got it figured out! 😃
